#!/usr/bin/env python
import sys

print '\r'+' '*80+'\r[|---------]    importing os',
sys.stdout.flush()
import os

print '\r'+' '*80+'\r[||--------]    importing wx',
sys.stdout.flush()
try:
    import wx
except ImportError:
    print "kokopelli error: wx import failed!"
    sys.exit(1)
print '\r'+' '*80+'\r[|||||-----]    importing koko',
sys.stdout.flush()


import koko
koko.BASE_DIR = os.path.abspath(os.getcwd())+'/'
if '.app' in sys.argv[0]:
    koko.BUNDLED = True
    sys.path.append('')
    os.chdir(koko.BASE_DIR+'../../..')
else:
    koko.BUNDLED = False

while len(sys.argv) > 1:
    if sys.argv[1] == '--debug':
        import subprocess
        python = 'python-64' if 'Darwin' in os.uname() else 'python'
        subprocess.call(['gdb', '--quiet',
                         '--eval-command',
                         'run %s %s' % (sys.argv[0], ' '.join(sys.argv[2:])),
                         '--eval-command', 'cont',
                         '--eval-command', 'quit', python])
        sys.exit(0)
    elif sys.argv[1] in ['--help', '-h']:
        print '''Usage:
  kokopelli [--help|-h] [FILENAME]'

  Options:
    --help    Print this message and exit

  Arguments:
    FILENAME    Target file to open'''
        sys.exit(0)
    else:
        break


print '\r'+' '*80+'\r[||||||----]    importing koko.app',
sys.stdout.flush()
from koko.app import App


if __name__ == '__main__':
    print '\r'+' '*80+'\r[||||||||||]    starting...',
    sys.stdout.flush()
    wx.Log.EnableLogging(False)
    app = App()
    print '\r'+' '*80+'\r',
    sys.stdout.flush()
    app.MainLoop()
